"""Add disappearing_timer

Revision ID: 5e973197c656
Revises: b71cc4f07ab7
Create Date: 2026-06-28 12:06:40.856022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e973197c656'
down_revision: Union[str, Sequence[str], None] = 'b71cc4f07ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('disappearing_timer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'disappearing_timer')
    # ### end Alembic commands ###
